### ISSUE TITLE
README user must modifiy AUTHORITY_URL

### ISSUE THREAD

**Issue by mark1010** [microsoftgraph/python-sample-console-app#10]
The README is missing the need to change the AUTHORITY_URL,  

from:
AUTHORITY_URL = 'https://login.microsoftonline.com/common'

to:
AUTHORITY_URL = 'https://login.microsoftonline.com/contoso.onmicrosoft.com'

as per:
https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/ADAL-basics

else the example fails with:

`AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Device Code request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials....`

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
