### ISSUE TITLE
bad handshake

### ISSUE THREAD

**Issue by TakahiroW4047** [microsoftgraph/python-sample-console-app#2]
Hello,

I followed the tutorial, and registered in the Azure AD as native app, but got the following error when I updated the Client ID. I've searched everywhere within Azure documentations, and googled SSL related issues, but could not get this error to go away. Has there been an update within ADAL that needs further updates?

requests.exceptions.SSLError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
