### ISSUE TITLE
authenticate without browser

### ISSUE THREAD

**Issue by mwe-bixeng** [microsoftgraph/python-sample-console-app#3]
Is it possible to authenticate without using a browser?
I want to be able to parse a onenote file in onedrive without having to authenticate through a browser (like in oauth2client)

**Comment by waza-ari** [comment]
Really, usually you want to use an API to **automate** somethin, that is, ideally, without a user needing to response to a browser that is being opened.

**Comment by genomics-admin** [comment]
I would echo the same, it kinda kills the automation if we need to also add manual elements in between. If there's any document on how to accomplish that. Please point us towards that.

Thanks.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
