### ISSUE TITLE
profile_photo helper function does not generate correct endpoint for photos other than 'me'

### ISSUE THREAD

**Issue by thehatchcloud** [microsoftgraph/python-sample-console-app#6]
When running the ```profile_photo``` function in ```helpers.py``` to get the photo of an account other than 'me', the incorrect endpoint url is generated.

```profile_photo(session, user_id='ahamilton@example.com', save_as='ahamilton.jpg')```
Expected endpoint:
```/users/ahamilton@example.com/photo/$value```

Actual endpoint:
```/users/ahamilton@example.com/$value```

Calling this function with an account other than 'me' results in a 400 error.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
